[build]
  command = "yarn build && yarn build-storybook"
  publish = "dist"
  
[context.production]
  command = "yarn test:unit && yarn build && yarn build-storybook"

[[redirects]]
  from = "/storybook"
  to = "/storybook/"
  status = 301
  force = true

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/storybook/*.(js|mjs)"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/storybook/*.(css)"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/storybook/*.(html)"
    [headers.values]
    Content-Type = "text/html"