[build]
  command = "yarn build && yarn build-storybook"
  publish = "dist"
  
[context.production]
  command = "yarn test:unit && yarn build && yarn build-storybook"

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/?path=/docs/product-widget--docs"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/storybook/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
    [headers.values]
    Content-Type = "application/javascript"