[build]
  command = "yarn build && yarn build-storybook"
  publish = "dist"
  
[context.production]
  command = "yarn test:unit && yarn build && yarn build-storybook"

[[redirects]]
  from = "/storybook"
  to = "/storybook/"
  status = 301
  force = true

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/storybook/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/storybook/*.html"
    [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/storybook/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/storybook/**/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"