[build]
  command = "yarn build && yarn build-storybook"
  publish = "dist"
  
[context.production]
  command = "yarn test:unit && yarn build && yarn build-storybook"

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/storybook/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
    [headers.values]
    Content-Type = "text/html"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/storybook/*.js"
    [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/storybook/sb-manager/*.js"
    [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/storybook/sb-addons/*.js"
    [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/storybook/sb-preview/*.js"
    [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"